spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clothing_store
    username: postgres
    password: baiel123
  security:
    jwt:
      secret_key: peaksofthousejava18


server:
  port: 9999

